### ISSUE TITLE
Skipper as sidecar and features for ingress

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#411]
In order to provide features like a service mesh istio or linkerd does we discussed in public google documents what features we want to support in the future.

Docs:
- [Skipper's role in Kubernetes](https://docs.google.com/document/d/1OLMO4hawaP8WfCQxLOMYh7coYfpgqfeVi9IxWApo1gg/edit#heading=h.oth6augb0h6y)
- [kubernetes sidecar proxy](https://docs.google.com/document/d/1tXVy0aWRFw8eV95OY85oIOeRO3ZzEJlMlXYl7l9uLOg/edit#heading=h.r2oli1vo9yt5)

Features that I want to have (I will create separate issues and link it from here, detailed discussions should happen on those):

- [x] OAuth/JWT token injection for the proxied app #412 , waits for #366 
- [x] OAuth/JWT validation for the proxied app #413 , waits for #366 
- [ ] service mesh #420 integrated with service discovery that can be integrated by the user (maybe as plugin), such that you can integrate your custom service discovery in case you can not use a default, for example Linkerd uses Finagle. 
  - Service discovery could be also hard coded routes in skipper sidecar proxy to opt-in and tune per application. An enhancement that would be required to make it more usable is to implement http forward proxy to skipper, such that all calls passing skipper. 
- [x] Loadbalancer support, which enables `ingress -> endpoints` circumventing service (`ingress -> svc -> endpoints`). This would also required to enable service mesh #499
- [x] Opentracing-API: inject tracing headers for proxied app if the application does not inject the headers itself #421
- [x] Opentracing-API Jaegr: https://github.com/skipper-plugins/opentracing/issues/1
<s>- [ ] OpenAPI (swagger) integration: for example: skipper could read the configuration of authorization from the OpenAPI spec or do validations and enforce these rules #418 </s>
- [x] Retries with exponential backoff for HTTP client calls #422
- [x] Circuit breaker for HTTP client calls #419
- [x] rate limiting #414

**Comment by szuecs** [comment]
There is one missing issue, that we might do or not, but I think this epic is now fine to close.
